version: '3'
services:
  php:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=sos_teste
    volumes:
      - ./data:/var/lib/mysql
      - ./bd/sos.sql:/docker-entrypoint-initdb.d/dump.sql
