version: '3'
services:
  php:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=sos_teste
    volumes:
      - ./data:/var/lib/mysql
      - ./bd/sos.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: myuser
      WORDPRESS_DB_PASSWORD: mypassword
      WORDPRESS_DB_NAME: sos_teste
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress: {}
